[CmdletBinding()]
param(
    [string]$RepositoryRoot
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
    $RepositoryRoot = Split-Path -Parent $PSScriptRoot
}

$root = [System.IO.Path]::GetFullPath($RepositoryRoot)
$sourceExtensions = @('.cs', '.cshtml', '.js', '.css', '.html', '.json', '.ps1')
$separator = [System.IO.Path]::DirectorySeparatorChar
$ignoredSegments = @(
    ('{0}.git{0}' -f $separator)
    ('{0}bin{0}' -f $separator)
    ('{0}obj{0}' -f $separator)
    ('{0}node_modules{0}' -f $separator)
    ('{0}App_Data{0}' -f $separator)
    ('{0}uploads{0}' -f $separator)
)

function Get-RelativePath([string]$path) {
    $fullPath = [System.IO.Path]::GetFullPath($path)
    if (-not $fullPath.StartsWith($root, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Path is outside repository root: $fullPath"
    }
    return $fullPath.Substring($root.Length).TrimStart('\', '/').Replace('\', '/')
}

function Test-IsIgnored([string]$path) {
    $normalized = [System.IO.Path]::GetFullPath($path)
    foreach ($segment in $ignoredSegments) {
        if ($normalized.IndexOf($segment, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
            return $true
        }
    }
    return $false
}

function Get-SourceFiles {
    Get-ChildItem -LiteralPath $root -Recurse -File | Where-Object {
        $sourceExtensions -contains $_.Extension.ToLowerInvariant() -and -not (Test-IsIgnored $_.FullName)
    }
}

$sourceFiles = @(Get-SourceFiles | Sort-Object { Get-RelativePath $_.FullName })
$largeFiles = foreach ($file in $sourceFiles) {
    $lineCount = [System.IO.File]::ReadAllLines($file.FullName).Length
    if ($lineCount -gt 500) {
        [PSCustomObject]@{
            Path = Get-RelativePath $file.FullName
            Lines = $lineCount
        }
    }
}
$largeFiles = @($largeFiles | Sort-Object @{ Expression = 'Lines'; Descending = $true }, Path)

$wwwroot = Join-Path $root 'backend/wwwroot'
$duplicateStaticNames = @()
if (Test-Path -LiteralPath $wwwroot) {
    $duplicateStaticNames = @(Get-ChildItem -LiteralPath $wwwroot -Recurse -File |
        Group-Object Name |
        Where-Object Count -gt 1 |
        Sort-Object Name)
}

$viewReferences = foreach ($file in $sourceFiles | Where-Object Extension -in @('.cshtml', '.html')) {
    $text = [System.IO.File]::ReadAllText($file.FullName)
    $matches = [regex]::Matches($text, '(?i)(?:src|href)\s*=\s*["'']([^"''?#]+(?:\.js|\.css))[^"'']*["'']')
    foreach ($match in $matches) {
        [PSCustomObject]@{
            View = Get-RelativePath $file.FullName
            Asset = $match.Groups[1].Value
        }
    }
}
$viewReferences = @($viewReferences | Sort-Object View, Asset -Unique)

$entryPoints = @(
    'backend/Program.cs',
    'backend/Views/_ViewStart.cshtml',
    'backend/Views/Shared/_Layout.cshtml',
    'backend/wwwroot/index.html',
    'backend/wwwroot/detail.html',
    'backend/wwwroot/reader.html',
    'package.json'
) | Where-Object { Test-Path -LiteralPath (Join-Path $root $_) }

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Codebase Baseline')
$lines.Add('')
$lines.Add('Generated by `tools/codebase-baseline.ps1`. Duplicate names are review candidates, not evidence that a file is safe to delete.')
$lines.Add('')
$lines.Add('## Entry points')
$lines.Add('')
foreach ($path in $entryPoints) {
    $lines.Add("- ``$path``")
}
$lines.Add('')
$lines.Add('## Files over 500 lines')
$lines.Add('')
$lines.Add('| Lines | File |')
$lines.Add('| ---: | --- |')
foreach ($file in $largeFiles) {
    $lines.Add("| $($file.Lines) | ``$($file.Path)`` |")
}
$lines.Add('')
$lines.Add('## Duplicate static filenames (review candidates only)')
$lines.Add('')
if ($duplicateStaticNames.Count -eq 0) {
    $lines.Add('- None.')
} else {
    foreach ($group in $duplicateStaticNames) {
        $paths = @($group.Group | ForEach-Object { Get-RelativePath $_.FullName } | Sort-Object)
        $lines.Add("- **$($group.Name)**")
        foreach ($path in $paths) {
            $lines.Add("  - ``$path``")
        }
    }
}
$lines.Add('')
$lines.Add('## View asset references')
$lines.Add('')
$lines.Add('| View | Asset |')
$lines.Add('| --- | --- |')
foreach ($reference in $viewReferences) {
    $lines.Add("| ``$($reference.View)`` | ``$($reference.Asset)`` |")
}
$lines.Add('')
$lines.Add('## Reproducible verification commands')
$lines.Add('')
$lines.Add('```powershell')
$lines.Add("powershell -NoProfile -ExecutionPolicy Bypass -File './tools/codebase-baseline.ps1'")
$lines.Add("dotnet test './backend.Tests/MangaNPK.Tests.csproj' -c Release --no-restore")
$lines.Add("dotnet build './backend/MangaNPK.csproj' -c Release --no-restore")
$lines.Add("Get-ChildItem './backend','./backend.Tests' -Recurse -File | Where-Object { `$_.Extension -in '.js','.cjs' -and `$_.FullName -notmatch '[\\/](bin|obj|node_modules|App_Data|uploads)[\\/]' } | ForEach-Object { node --check `$_.FullName }")
$lines.Add("Get-ChildItem './backend.Tests/js' -Filter '*.test.cjs' -File | ForEach-Object { node --test `$_.FullName }")
$lines.Add("dotnet test './backend.Tests/MangaNPK.Tests.csproj' -c Release --filter 'FullyQualifiedName~SourceEncodingTests' --no-restore")
$lines.Add('```')
$lines.Add('')
$lines.Add('## Verification notes')
$lines.Add('')
$lines.Add('- Verified on 2026-07-15: Release build succeeded with 0 warnings and 0 errors.')
$lines.Add('- Backend tests: 51 passed, 0 failed.')
$lines.Add('- JavaScript syntax: 30 source/test files passed `node --check`.')
$lines.Add('- JavaScript tests: 5 test files, 10 tests passed.')
$lines.Add('- Encoding regression: strict UTF-8 and known-mojibake tests passed.')
$lines.Add('- Database/browser smoke test is not marked as passed: the LocalDB API returned an unexpected error and no application was listening on port 5274.')
$lines.Add('- No intentional visual, DOM-contract or API behavior change was made. Phase 2 decomposed admin controllers, extracted chapter/catalog/MangaDex/title-draft persistence, and corrected already-corrupted Vietnamese fallback text.')

$lines -join [Environment]::NewLine
